name: PartnersUI
author: Ameer4Real, Mikeygio10
main: Ameer4Real\PartnersUI
version: 1.0
description: PartnersUI
api: [3.0.0, 4.0.0]
commands:
    partners:
        default: true
        description: List of servers partners
