---
#Here you can change the messages that will display
#Use "§" as a color symbol
#Use "\n" to go to the next line
#The title of the menu
Title: "§0§lPartners"
#The content of the menu (Description)
Content: "§cComing Soon"
#Returns button name
Button: "§cExit"
...
